import type { Event } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    name: 'Tech Innovators Conference 2025',
    category: 'Conference',
    date: '2025-11-15T09:00:00.000Z',
    location: 'Silicon Valley, CA',
    description:
      'Join the brightest minds in technology as they discuss the future of AI, blockchain, and quantum computing. A three-day event full of keynotes, workshops, and networking opportunities.',
    promotionalText: "Don't miss the biggest tech conference of the year! Get your early bird tickets now and be part of the future.",
    image: 'https://placehold.co/600x400',
    targetAudience: 'Professionals',
  },
  {
    id: '2',
    name: 'Annual Charity Gala',
    category: 'Gala',
    date: '2025-12-01T18:00:00.000Z',
    location: 'Metropolitan Museum, New York',
    description: 'An elegant evening of dining, dancing, and auctions to support children\'s education. All proceeds go to the "Future Minds" foundation.',
    promotionalText: 'Join us for a night of elegance and purpose. Your presence can change a child\'s life. Reserve your table today!',
    image: 'https://placehold.co/600x400',
    targetAudience: 'Philanthropists',
  },
  {
    id: '3',
    name: 'Indie Music Fest',
    category: 'Music',
    date: '2025-10-25T14:00:00.000Z',
    location: 'Green Park, London',
    description: 'Discover your new favorite band at the Indie Music Fest. A full day of live performances from emerging artists across various genres.',
    promotionalText: 'Vibes, music, and sunshine! Grab your friends and get ready for an unforgettable day at Indie Music Fest.',
    image: 'https://placehold.co/600x400',
    targetAudience: 'Young Adults',
  },
  {
    id: '4',
    name: 'Startup Pitch Night',
    category: 'Networking',
    date: '2025-11-05T19:00:00.000Z',
    location: 'WeWork, Berlin',
    description: 'Watch the next generation of entrepreneurs pitch their ideas to a panel of investors. Network with founders, VCs, and innovators.',
    promotionalText: 'The next unicorn might be here. Witness innovation in action at Startup Pitch Night!',
    image: 'https://placehold.co/600x400',
    targetAudience: 'Entrepreneurs',
  },
  {
    id: '5',
    name: 'Modern Art Exhibition',
    category: 'Art',
    date: '2025-10-20T10:00:00.000Z',
    location: 'The Louvre, Paris',
    description: 'Explore a curated collection of modern art from around the world. Featuring works by both renowned and up-and-coming artists.',
    promotionalText: 'Immerse yourself in creativity. The Modern Art Exhibition is a must-see for art lovers.',
    image: 'https://placehold.co/600x400',
    targetAudience: 'Art Enthusiasts',
  },
  {
    id: '6',
    name: 'Oktoberfest Celebration',
    category: 'Festival',
    date: '2025-10-18T12:00:00.000Z',
    location: 'Theresienwiese, Munich',
    description: 'Experience the world-famous Oktoberfest! Enjoy traditional Bavarian beer, food, music, and culture in a lively and festive atmosphere.',
    promotionalText: 'Prost! The world\'s largest beer festival is calling. Join us for an authentic Oktoberfest experience.',
    image: 'https://placehold.co/600x400',
    targetAudience: 'General Audience',
  },
  {
    id: '7',
    name: 'Advanced JavaScript Workshop',
    category: 'Workshop',
    date: '2025-11-22T09:30:00.000Z',
    location: 'Online',
    description: 'Deep dive into advanced JavaScript concepts like closures, promises, and the event loop. This workshop is for experienced developers looking to master their skills.',
    promotionalText: 'Level up your JS skills. This intensive workshop will make you a JavaScript master. Limited spots available!',
    image: 'https://placehold.co/600x400',
    targetAudience: 'Developers',
  },
  {
    id: '8',
    name: 'Community Hackathon',
    category: 'Hackathon',
    date: '2025-12-05T10:00:00.000Z',
    location: 'Google Campus, London',
    description: 'A 48-hour coding marathon to build innovative solutions for social good. Collaborate with other developers, designers, and thinkers.',
    promotionalText: 'Code for a cause! Join our Community Hackathon and make a difference with your skills.',
    image: 'https://placehold.co/600x400',
    targetAudience: 'Developers',
  },
];
